-- Run this in Supabase SQL Editor once.

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null,
  client_email text,
  sender_company_name text,
  total numeric(14, 2) default 0,
  currency text not null,
  template text not null,
  privacy_policy_accepted boolean not null default false,
  downloaded_at timestamptz,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

-- Since backend currently uses publishable key in Supabase API mode,
-- allow inserts for anon/authenticated roles only when privacy is accepted.
alter table public.invoices enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.invoices to anon, authenticated;

drop policy if exists allow_invoice_insert_when_privacy_confirmed on public.invoices;
drop policy if exists allow_invoice_insert on public.invoices;

-- Permissive policy: allow any insert from anon/authenticated users
-- privacy_policy_accepted is enforced at app level
create policy allow_invoice_insert
  on public.invoices
  for insert
  to anon, authenticated
  with check (true);

-- Optional: allow reads from dashboard queries with service role only.
-- No public select policy is created here.
