create table if not exists public.negotiations (
  id bigint generated by default as identity primary key,
  invoice_id bigint references public.invoices(id) on delete cascade,
  sender_profile_id uuid references public.profiles(id),
  proposed_total numeric(14,2),
  message text,
  status text not null default 'pending'
    check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now()
);
