create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  invoice_id bigint references public.invoices(id) on delete cascade,
  type text not null, -- 'quote_sent' | 'counter_offer' | 'accepted' | 'rejected'
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);
